/*
 * KrutPreviewWindow.java
 *
 * Created on 5. juni 2007, 16:30
 */

package net.sourceforge.krut.ui;

/**
 *
 * @author  Jonas
 */
/** Netbeans-autogenerated class containing the preview window. */
public class KrutPreviewWindow extends javax.swing.JFrame {
    
    /** Creates new form KrutPreviewWindow */
    public KrutPreviewWindow() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KrutPreviewWindow().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
